import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  fr: {
    'nav.dashboard': 'Tableau de bord', 'nav.vehicles': 'Véhicules', 'nav.calendar': 'Calendrier', 'nav.analytics': 'Analytiques', 'nav.alerts': 'Alertes', 'nav.emailActivity': 'Activité Email', 'nav.settings': 'Paramètres', 'nav.users': 'Utilisateurs', 'nav.logout': 'Se déconnecter',
    'dashboard.title': 'Tableau de bord', 'dashboard.subtitle': 'Surveillez l\'état de synchronisation de votre flotte', 'dashboard.allSynced': 'Tous les systèmes synchronisés', 'dashboard.allRunning': 'Tout fonctionne correctement', 'dashboard.attentionRequired': 'Attention requise', 'dashboard.needsReview': 'Certains éléments nécessitent votre attention', 'dashboard.criticalIssue': 'Problème critique', 'dashboard.immediateAction': 'Action immédiate requise', 'dashboard.lastSync': 'Dernière synchro :', 'dashboard.emailsToday': 'emails aujourd\'hui', 'dashboard.activeVehicles': 'Véhicules actifs', 'dashboard.currentlyBooked': 'actuellement réservés', 'dashboard.emailsProcessed': 'Emails traités', 'dashboard.last24h': 'Dernières 24 heures', 'dashboard.activeAlerts': 'Alertes actives', 'dashboard.noCritical': 'Aucune alerte critique', 'dashboard.calendarSyncs': 'Synchros calendrier', 'dashboard.calendarsConnected': 'Calendriers connectés', 'dashboard.pending': 'en attente', 'dashboard.noActiveAlerts': 'Aucune alerte active', 'dashboard.recentActivity': 'Activité email récente', 'dashboard.noRecentActivity': 'Aucune activité récente', 'dashboard.never': 'Jamais',
    'vehicles.title': 'Véhicules', 'vehicles.subtitle': 'Gérez votre flotte et vos annonces', 'vehicles.addVehicle': 'Ajouter un véhicule', 'vehicles.search': 'Rechercher des véhicules...', 'vehicles.allStatus': 'Tous les statuts', 'vehicles.available': 'Disponible', 'vehicles.booked': 'Réservé', 'vehicles.maintenance': 'Maintenance', 'vehicles.allPlatforms': 'Toutes les plateformes', 'vehicles.noVehicles': 'Aucun véhicule trouvé', 'vehicles.noVehiclesDesc': 'Ajoutez votre premier véhicule pour commencer', 'vehicles.adjustFilters': 'Essayez d\'ajuster vos filtres', 'vehicles.activeBooking': 'Réservation active', 'vehicles.guest': 'Client :', 'vehicles.ref': 'Réf :', 'vehicles.checkIn': 'Arrivée :', 'vehicles.checkOut': 'Départ :', 'vehicles.duration': 'Durée :', 'vehicles.via': 'via', 'vehicles.day': 'jour', 'vehicles.days': 'jours', 'vehicles.hour': 'heure', 'vehicles.hours': 'heures', 'vehicles.autoSync': 'Synchroniser automatiquement', 'vehicles.autoSyncShort': 'Synchro auto', 'vehicles.advancedFilters': 'Filtres avancés', 'vehicles.viewArchived': 'Voir archivés', 'vehicles.archived': 'Archivés', 'vehicles.reset': 'Réinitialiser', 'vehicles.searchPlaceholder': 'Rechercher par nom, plaque ou VIN...', 'vehicles.status': 'Statut', 'vehicles.platform': 'Plateforme', 'vehicles.calendar': 'Calendrier', 'vehicles.allCalendars': 'Tous les calendriers', 'vehicles.noCalendar': 'Aucun calendrier', 'vehicles.confirmDelete': 'Êtes-vous sûr de vouloir supprimer {{name}} ?', 'vehicles.confirmArchive': 'Voulez-vous {{action}} {{name}} ?', 'vehicles.archive': 'archiver', 'vehicles.unarchive': 'désarchiver', 'vehicles.deleteSuccess': 'Véhicule supprimé avec succès', 'vehicles.archiveSuccess': 'Véhicule archivé', 'vehicles.unarchiveSuccess': 'Véhicule désarchivé', 'vehicles.syncLimitReached': 'Limite de synchronisation atteinte', 'vehicles.syncLimitDesc': 'Vous avez déjà synchronisé 3 fois aujourd\'hui. Réessayez demain.', 'vehicles.syncing': 'Synchronisation en cours...', 'vehicles.syncSuccess': 'Synchronisation réussie', 'vehicles.syncError': 'Erreur de synchronisation',
    'addVehicle.title': 'Ajouter un nouveau véhicule', 'addVehicle.autoFill': 'Remplissage automatique', 'addVehicle.vin': 'Numéro VIN', 'addVehicle.licensePlate': 'Plaque d\'immatriculation', 'addVehicle.autoFillButton': 'Remplir automatiquement', 'addVehicle.lookingUp': 'Recherche du véhicule...', 'addVehicle.name': 'Nom du véhicule *', 'addVehicle.namePlaceholder': 'ex: Tesla Model 3 - Blanche', 'addVehicle.year': 'Année', 'addVehicle.make': 'Marque', 'addVehicle.model': 'Modèle', 'addVehicle.platforms': 'Plateformes listées', 'addVehicle.calendar': 'Calendrier', 'addVehicle.noCalendar': 'Aucun calendrier', 'addVehicle.googleCalendar': 'Google Agenda', 'addVehicle.outlookCalendar': 'Calendrier Outlook', 'addVehicle.cancel': 'Annuler', 'addVehicle.adding': 'Ajout...', 'addVehicle.add': 'Ajouter le véhicule',
    'calendar.title': 'Calendrier', 'calendar.subtitle': 'Voir toutes les réservations de votre flotte', 'calendar.allVehicles': 'Tous les véhicules', 'calendar.platform': 'Plateforme :', 'calendar.platforms': 'Plateformes', 'calendar.unknownVehicle': 'Véhicule inconnu',
    'alerts.title': 'Alertes & Problèmes', 'alerts.active': 'alerte active', 'alerts.actives': 'alertes actives', 'alerts.critical': 'critique', 'alerts.allAlerts': 'Toutes les alertes', 'alerts.activeOnly': 'Actives', 'alerts.resolved': 'Résolues', 'alerts.allSeverity': 'Toutes les sévérités', 'alerts.warning': 'Avertissement', 'alerts.info': 'Info', 'alerts.allClear': 'Tout est clair !', 'alerts.noMatch': 'Aucune alerte ne correspond à vos filtres', 'alerts.resolution': 'Résolution :', 'alerts.resolvedOn': 'Résolu le', 'alerts.markResolved': 'Marquer comme résolu', 'alerts.dismiss': 'Ignorer',
    'alertType.vehicle_unclear': 'Nom de véhicule peu clair', 'alertType.dates_missing': 'Dates manquantes', 'alertType.ambiguous_update': 'Mise à jour ambiguë', 'alertType.sync_conflict': 'Conflit de synchronisation', 'alertType.low_confidence': 'Faible confiance', 'alertType.connection_error': 'Erreur de connexion',
    'email.title': 'Activité Email', 'email.subtitle': 'Journal d\'audit de tous les emails traités', 'email.search': 'Rechercher par sujet ou expéditeur...', 'email.allActions': 'Toutes les actions', 'email.synced': 'Synchronisé', 'email.blocked': 'Bloqué', 'email.pendingReview': 'En attente', 'email.ignored': 'Ignoré', 'email.noEmails': 'Aucun email trouvé', 'email.noProcessed': 'Aucun email n\'a encore été traité', 'email.adjustFilters': 'Essayez d\'ajuster vos filtres', 'email.noSubject': 'Aucun objet', 'email.eventType': 'Type d\'événement', 'email.confidence': 'Confiance', 'email.preview': 'Aperçu de l\'email', 'email.classificationOutput': 'Résultat de classification',
    'eventType.booking_confirmed': 'Réservation confirmée', 'eventType.booking_cancelled': 'Réservation annulée', 'eventType.booking_modified': 'Réservation modifiée', 'eventType.reminder': 'Rappel', 'eventType.unknown': 'Inconnu',
    'settings.title': 'Paramètres', 'settings.subtitle': 'Gérez vos connexions et préférences', 'settings.emailConnected': 'Email connecté', 'settings.emailNotConnected': 'Email non connecté', 'settings.connectedVia': 'Connecté via', 'settings.connectToStart': 'Connecter pour commencer la synchro', 'settings.calendarConnected': 'Calendrier connecté', 'settings.calendarNotConnected': 'Calendrier non connecté', 'settings.syncingTo': 'Synchronisation vers', 'settings.optionalSync': 'Optionnel - synchroniser vers le calendrier', 'settings.emailConnection': 'Connexion Email', 'settings.emailConnectionDesc': 'Connectez votre Gmail ou Outlook pour recevoir automatiquement les notifications de réservation', 'settings.calendarSync': 'Synchronisation calendrier', 'settings.calendarSyncDesc': 'Synchronisez les réservations avec votre calendrier préféré pour une vue unifiée', 'settings.clickToConnect': 'Cliquer pour connecter', 'settings.connected': 'Connecté', 'settings.icalIntegration': 'Intégration iCal', 'settings.icalDesc': 'Partagez les calendriers de réservation avec les plateformes de location', 'settings.setupInstructions': 'Instructions de configuration', 'settings.icalInstructions': 'Après avoir ajouté des véhicules, vous recevrez des URL iCal uniques pour chaque véhicule. Copiez ces URL dans Turo, Getaround ou d\'autres plateformes pour synchroniser vos réservations et éviter les doubles réservations.', 'settings.language': 'Langue', 'settings.languageDesc': 'Choisissez la langue de l\'interface', 'settings.french': 'Français', 'settings.english': 'English', 'settings.general': 'Général', 'settings.notifications': 'Notifications', 'settings.calendars': 'Calendriers', 'settings.subscription': 'Abonnement', 'settings.maintenance': 'Maintenance', 'settings.revenue': 'Revenus', 'settings.autoDetection': 'Détection automatique des véhicules', 'settings.autoDetectionDesc': 'Ajoutez vos véhicules automatiquement via les emails', 'settings.autoDetectionInfo': 'FleetSync détecte automatiquement les nouveaux véhicules mentionnés dans vos emails de réservation (Turo, Getaround, Hunos Rent) et vous propose de les ajouter à votre flotte.', 'settings.featureActive': 'Fonctionnalité active', 'settings.featureActiveDesc': 'Connectez votre email ci-dessus et les nouveaux véhicules seront détectés automatiquement lors de la réception des confirmations de réservation.', 'settings.calendarIntegrations': 'Intégrations de calendrier', 'settings.comingSoon': 'Bientôt disponible', 'settings.maintenanceComingSoon': 'Les intégrations de maintenance seront disponibles prochainement', 'settings.revenueComingSoon': 'Les intégrations de revenus seront disponibles prochainement',
    'notifPrefs.title': 'Préférences de notifications', 'notifPrefs.description': 'Choisissez les notifications que vous souhaitez recevoir', 'notifPrefs.upcomingBookings': 'Réservations imminentes', 'notifPrefs.upcomingBookingsDesc': 'Notification 24h avant le début d\'une réservation', 'notifPrefs.vehicleReturns': 'Retours de véhicules', 'notifPrefs.vehicleReturnsDesc': 'Notification le jour du retour prévu d\'un véhicule', 'notifPrefs.statusUpdates': 'Mises à jour de statut', 'notifPrefs.statusUpdatesDesc': 'Notification lors du changement de statut d\'une réservation', 'notifPrefs.syncErrors': 'Erreurs de synchronisation', 'notifPrefs.syncErrorsDesc': 'Alerte en cas de problème de synchronisation', 'notifPrefs.newAlerts': 'Nouvelles alertes', 'notifPrefs.newAlertsDesc': 'Notification lors de la création d\'une alerte', 'notifPrefs.saved': 'Préférences enregistrées',
    'calendarIntegrations.backendRequiredTitle': 'Serveur FleetSync', 'calendarIntegrations.backendRequiredDesc': 'Les calendriers Google et Outlook sont gérés par le serveur FleetSync. Ajoutez les identifiants OAuth du backend pour pousser les événements vers l\'extérieur. Sans eux, les réservations restent dans le calendrier local.', 'calendarIntegrations.googleCalendar': 'Google Calendar', 'calendarIntegrations.googleCalendarDesc': 'Synchronisez vos réservations avec Google Calendar pour une vue unifiée', 'calendarIntegrations.googleConnected': 'Synchronisation active avec Google Calendar', 'calendarIntegrations.outlookCalendar': 'Outlook Calendar', 'calendarIntegrations.outlookCalendarDesc': 'Intégrez vos réservations à votre calendrier Outlook professionnel', 'calendarIntegrations.outlookConnected': 'Synchronisation active avec Outlook Calendar', 'calendarIntegrations.backendRequired': 'Ajoutez les identifiants OAuth du serveur FleetSync pour pousser ce calendrier à l\'extérieur', 'calendarIntegrations.disconnected': 'Calendrier déconnecté',
    'integrationCard.connected': 'Connecté', 'integrationCard.notConnected': 'Non connecté', 'integrationCard.connect': 'Connecter', 'integrationCard.connecting': 'Connexion...', 'integrationCard.disconnect': 'Déconnecter', 'integrationCard.disconnecting': 'Déconnexion...',
    'notification.new_booking': 'Nouvelle réservation', 'notification.booking_cancelled': 'Réservation annulée', 'notification.booking_modified': 'Réservation modifiée', 'notification.vehicle_status_change': 'Statut véhicule modifié', 'notification.maintenance_reminder': 'Rappel de maintenance', 'notification.sync_error': 'Erreur de synchronisation', 'notification.alert_created': 'Nouvelle alerte',
    'notification.New Booking': 'Nouvelle réservation', 'notification.Booking Cancelled': 'Réservation annulée', 'notification.Booking Modified': 'Réservation modifiée', 'notification.Vehicle Status Changed': 'Statut véhicule modifié', 'notification.Maintenance Reminder': 'Rappel de maintenance', 'notification.Sync Error': 'Erreur de synchronisation', 'notification.New Alert': 'Nouvelle alerte',
    'notifications.title': 'Notifications', 'notifications.unreadCount': '{{count}} non lue{{count > 1 ? "s" : ""}}', 'notifications.markAllRead': 'Tout marquer lu', 'notifications.empty': 'Aucune notification pour le moment',
    'analytics.title': 'Tableau de bord analytique', 'analytics.subtitle': 'Vue d\'ensemble de vos performances et métriques', 'analytics.totalBookings': 'Total réservations', 'analytics.monthlyRevenue': 'Revenus du mois', 'analytics.weeklyRevenue': 'Revenus de la semaine', 'analytics.activeBookings': 'Réservations actives', 'analytics.revenue': 'Revenus', 'analytics.utilization': 'Utilisation', 'analytics.platforms': 'Plateformes', 'analytics.revenueEvolution': 'Évolution des revenus', 'analytics.revenueEvolutionDesc': 'Revenus nets des 6 derniers mois', 'analytics.revenueLabel': 'Revenus', 'analytics.revenueEuro': 'Revenus (€)', 'analytics.utilizationRate': 'Taux d\'utilisation des véhicules', 'analytics.utilizationRateDesc': 'Pourcentage d\'utilisation ce mois-ci', 'analytics.utilizationLabel': 'Utilisation', 'analytics.utilizationPercent': 'Utilisation (%)', 'analytics.platformDistribution': 'Distribution par plateforme', 'analytics.platformDistributionDesc': 'Répartition des réservations par plateforme',
    'clients.title': 'Clients', 'clients.subtitle': 'Gérez vos clients et leur historique', 'clients.addCustomer': 'Ajouter un client', 'clients.searchPlaceholder': 'Rechercher par nom, email ou téléphone...', 'clients.allPlatforms': 'Toutes les plateformes', 'clients.manual': 'Manuel', 'clients.loading': 'Chargement...', 'clients.noCustomersFound': 'Aucun client trouvé', 'clients.noCustomers': 'Aucun client', 'clients.adjustFilters': 'Essayez de modifier vos filtres', 'clients.addFirstCustomer': 'Ajoutez votre premier client', 'clients.bookings': 'Réservations',
    'users.title': 'Gestion des utilisateurs', 'users.subtitle': 'Gérez les membres de votre équipe et leurs permissions', 'users.inviteUser': 'Inviter un utilisateur', 'users.searchPlaceholder': 'Rechercher par nom ou email...', 'users.role': 'Rôle', 'users.allRoles': 'Tous les rôles', 'users.admin': 'Admin', 'users.manager': 'Gestionnaire', 'users.user': 'Utilisateur', 'users.noName': 'Sans nom', 'users.department': 'Département', 'users.edit': 'Modifier', 'users.noUsersFound': 'Aucun utilisateur trouvé', 'users.updateSuccess': 'Utilisateur mis à jour avec succès', 'users.deleteSuccess': 'Utilisateur supprimé avec succès', 'users.deleteError': 'Erreur lors de la suppression de l\'utilisateur', 'users.confirmDelete': 'Êtes-vous sûr de vouloir supprimer {{name}} ?', 'users.accessDenied': 'Accès refusé', 'users.accessDeniedDesc': 'Vous n\'avez pas les permissions pour accéder à cette page.',
    'subscription.fleetSyncPlan': 'Plan FleetSync', 'subscription.activeSubscription': 'Abonnement actif', 'subscription.active': 'Actif', 'subscription.basePlan': 'Abonnement de base', 'subscription.vehicle': 'véhicule', 'subscription.vehicles': 'véhicules', 'subscription.month': 'mois', 'subscription.totalPerMonth': 'Total par mois', 'subscription.pricingTiers': 'Tarification dégressive', 'subscription.autoDegressivePricing': 'Plus votre flotte grandit, moins vous payez par véhicule', 'subscription.includedFeatures': 'Fonctionnalités incluses', 'subscription.syncMultiPlatform': 'Synchronisation multi-plateformes', 'subscription.realTimeAlerts': 'Alertes en temps réel', 'subscription.calendarIntegration': 'Intégration calendrier', 'subscription.emailProcessing': 'Traitement automatique des emails', 'subscription.unlimitedBookings': 'Réservations illimitées', 'subscription.support': 'Support client', 'subscription.managePayment': 'Gérer le paiement', 'subscription.cancelSubscription': 'Annuler l\'abonnement', 'subscription.noCommitment': 'Sans engagement • Annulation à tout moment', 'subscription.contactSupport': 'Contactez le support pour gérer votre abonnement', 'subscription.stripePortalInfo': 'Pour activer la gestion des paiements Stripe, veuillez configurer l\'intégration Stripe dans votre app', 'subscription.portalError': 'Erreur lors de l\'ouverture du portail de paiement', 'subscription.fixedPrice': 'forfait', 'subscription.upTo': 'Jusqu\'à',
    'rgpd.title': 'Conformité RGPD', 'rgpd.subtitle': 'Gérez vos consentements et préférences de confidentialité', 'rgpd.consentGiven': 'Consentement complet', 'rgpd.consentPending': 'Consentement incomplet', 'rgpd.active': 'Actif', 'rgpd.incomplete': 'Incomplet', 'rgpd.lastUpdate': 'Dernière mise à jour', 'rgpd.emailProcessing': 'Traitement des emails de réservation', 'rgpd.emailProcessingDesc': 'J\'autorise FleetSync à traiter mes emails de réservation provenant des plateformes de location autorisées', 'rgpd.dataRetention': 'Conservation des données', 'rgpd.dataRetentionDesc': 'J\'accepte la conservation de mes données de réservation conformément à la politique de confidentialité', 'rgpd.allowedDomains': 'Domaines autorisés', 'rgpd.allowedDomainsDesc': 'FleetSync ne traitera que les emails provenant de ces domaines sécurisés :', 'rgpd.saveConsent': 'Enregistrer les préférences', 'rgpd.saving': 'Enregistrement...', 'rgpd.consentSaved': 'Préférences enregistrées', 'rgpd.dataRights': 'Conformément au RGPD, vous disposez d\'un droit d\'accès, de rectification, d\'effacement et de portabilité de vos données. Vous pouvez retirer votre consentement à tout moment. Pour exercer vos droits, contactez le support.', 'rgpd.backendRequired': 'Filtrage des emails', 'rgpd.backendRequiredDesc': 'Le serveur FleetSync ne traite que les emails importés dont l\'expéditeur appartient aux domaines autorisés.',
    'login.title': 'Connexion', 'login.subtitle': 'Accédez à votre compte FleetSync', 'login.email': 'Adresse email', 'login.emailPlaceholder': 'votre@email.com', 'login.emailRequired': 'L\'email est requis', 'login.emailInvalid': 'Veuillez entrer une adresse email valide', 'login.password': 'Mot de passe', 'login.passwordPlaceholder': '••••••••', 'login.passwordRequired': 'Le mot de passe est requis', 'login.passwordTooShort': 'Le mot de passe doit contenir au moins 6 caractères', 'login.rememberMe': 'Se souvenir de moi', 'login.forgotPassword': 'Mot de passe oublié ?', 'login.signIn': 'Se connecter', 'login.loggingIn': 'Connexion...', 'login.noAccount': 'Vous n\'avez pas de compte ?', 'login.signUp': 'S\'inscrire', 'login.backToHome': 'Retour à l\'accueil', 'login.securityNote': 'Vos données sont chiffrées et sécurisées', 'login.success': 'Connexion réussie', 'login.failed': 'Échec de la connexion', 'login.orContinueWith': 'Ou continuer avec', 'login.continueWithGoogle': 'Continuer avec Google', 'login.googleLoginFailed': 'Échec de la connexion Google',
    'register.title': 'Créer un compte', 'register.subtitle': 'Commencez à utiliser FleetSync', 'register.name': 'Nom complet', 'register.namePlaceholder': 'Jean Dupont', 'register.nameRequired': 'Le nom est requis', 'register.email': 'Adresse email', 'register.emailPlaceholder': 'votre@email.com', 'register.emailRequired': 'L\'email est requis', 'register.emailInvalid': 'Veuillez entrer une adresse email valide', 'register.password': 'Mot de passe', 'register.passwordPlaceholder': '••••••••', 'register.passwordRequired': 'Le mot de passe est requis', 'register.passwordTooShort': 'Le mot de passe doit contenir au moins 6 caractères', 'register.createAccount': 'Créer le compte', 'register.creatingAccount': 'Création du compte...', 'register.alreadyHaveAccount': 'Vous avez déjà un compte ?', 'register.signIn': 'Se connecter', 'register.backToHome': 'Retour à l\'accueil', 'register.termsAgreement': 'En vous inscrivant, vous acceptez nos Conditions d\'utilisation et notre Politique de confidentialité', 'register.success': 'Compte créé avec succès', 'register.failed': 'Échec de la création du compte', 'register.orContinueWith': 'Ou continuer avec', 'register.continueWithGoogle': 'Continuer avec Google', 'register.googleSignupFailed': 'Échec de l\'inscription Google',
    'authCallback.processing': 'Traitement de l\'authentification...', 'authCallback.pleaseWait': 'Veuillez patienter pendant que nous traitons votre connexion', 'authCallback.loginSuccess': 'Connexion réussie', 'authCallback.loginFailed': 'Échec de la connexion', 'authCallback.noToken': 'Aucun jeton d\'authentification reçu',
    'login.continueWithMicrosoft': 'Continuer avec Microsoft', 'register.continueWithMicrosoft': 'Continuer avec Microsoft', 'login.microsoftLoginFailed': 'Échec de la connexion Microsoft', 'register.microsoftSignupFailed': 'Échec de l\'inscription Microsoft',
    },
  en: {
    'nav.dashboard': 'Dashboard', 'nav.vehicles': 'Vehicles', 'nav.calendar': 'Calendar', 'nav.analytics': 'Analytics', 'nav.alerts': 'Alerts', 'nav.emailActivity': 'Email Activity', 'nav.settings': 'Settings', 'nav.users': 'Users', 'nav.logout': 'Logout',
    'dashboard.title': 'Dashboard', 'dashboard.subtitle': 'Monitor your fleet synchronization status', 'dashboard.allSynced': 'All Systems Synced', 'dashboard.allRunning': 'Everything is running smoothly', 'dashboard.attentionRequired': 'Attention Required', 'dashboard.needsReview': 'Some items need your review', 'dashboard.criticalIssue': 'Critical Issue', 'dashboard.immediateAction': 'Immediate action required', 'dashboard.lastSync': 'Last sync:', 'dashboard.emailsToday': 'emails today', 'dashboard.activeVehicles': 'Active Vehicles', 'dashboard.currentlyBooked': 'currently booked', 'dashboard.emailsProcessed': 'Emails Processed', 'dashboard.last24h': 'Last 24 hours', 'dashboard.activeAlerts': 'Active Alerts', 'dashboard.noCritical': 'No critical alerts', 'dashboard.calendarSyncs': 'Calendar Syncs', 'dashboard.calendarsConnected': 'Calendars connected', 'dashboard.pending': 'pending', 'dashboard.noActiveAlerts': 'No active alerts', 'dashboard.recentActivity': 'Recent Email Activity', 'dashboard.noRecentActivity': 'No recent activity', 'dashboard.never': 'Never',
    'vehicles.title': 'Vehicles', 'vehicles.subtitle': 'Manage your fleet and platform listings', 'vehicles.addVehicle': 'Add Vehicle', 'vehicles.search': 'Search vehicles...', 'vehicles.allStatus': 'All Status', 'vehicles.available': 'Available', 'vehicles.booked': 'Booked', 'vehicles.maintenance': 'Maintenance', 'vehicles.allPlatforms': 'All Platforms', 'vehicles.noVehicles': 'No vehicles found', 'vehicles.noVehiclesDesc': 'Add your first vehicle to get started', 'vehicles.adjustFilters': 'Try adjusting your filters', 'vehicles.activeBooking': 'Active Booking', 'vehicles.guest': 'Guest:', 'vehicles.ref': 'Ref:', 'vehicles.checkIn': 'Check-in:', 'vehicles.checkOut': 'Check-out:', 'vehicles.duration': 'Duration:', 'vehicles.via': 'via', 'vehicles.day': 'day', 'vehicles.days': 'days', 'vehicles.hour': 'hour', 'vehicles.hours': 'hours', 'vehicles.autoSync': 'Auto Sync', 'vehicles.autoSyncShort': 'Sync', 'vehicles.advancedFilters': 'Advanced Filters', 'vehicles.viewArchived': 'View Archived', 'vehicles.archived': 'Archived', 'vehicles.reset': 'Reset', 'vehicles.searchPlaceholder': 'Search by name, plate or VIN...', 'vehicles.status': 'Status', 'vehicles.platform': 'Platform', 'vehicles.calendar': 'Calendar', 'vehicles.allCalendars': 'All Calendars', 'vehicles.noCalendar': 'No Calendar', 'vehicles.confirmDelete': 'Are you sure you want to delete {{name}}?', 'vehicles.confirmArchive': 'Do you want to {{action}} {{name}}?', 'vehicles.archive': 'archive', 'vehicles.unarchive': 'unarchive', 'vehicles.deleteSuccess': 'Vehicle deleted successfully', 'vehicles.archiveSuccess': 'Vehicle archived', 'vehicles.unarchiveSuccess': 'Vehicle unarchived', 'vehicles.syncLimitReached': 'Sync limit reached', 'vehicles.syncLimitDesc': 'You have already synced 3 times today. Try again tomorrow.', 'vehicles.syncing': 'Syncing...', 'vehicles.syncSuccess': 'Sync successful', 'vehicles.syncError': 'Sync error',
    'addVehicle.title': 'Add New Vehicle', 'addVehicle.autoFill': 'Auto-Fill Vehicle Details', 'addVehicle.vin': 'VIN', 'addVehicle.licensePlate': 'License Plate', 'addVehicle.autoFillButton': 'Auto-Fill Details', 'addVehicle.lookingUp': 'Looking up vehicle...', 'addVehicle.name': 'Vehicle Name *', 'addVehicle.namePlaceholder': 'e.g., Tesla Model 3 - White', 'addVehicle.year': 'Year', 'addVehicle.make': 'Make', 'addVehicle.model': 'Model', 'addVehicle.platforms': 'Listed Platforms', 'addVehicle.calendar': 'Calendar Provider', 'addVehicle.noCalendar': 'No Calendar', 'addVehicle.googleCalendar': 'Google Calendar', 'addVehicle.outlookCalendar': 'Outlook Calendar', 'addVehicle.cancel': 'Cancel', 'addVehicle.adding': 'Adding...', 'addVehicle.add': 'Add Vehicle',
    'calendar.title': 'Calendar', 'calendar.subtitle': 'View all bookings across your fleet', 'calendar.allVehicles': 'All Vehicles', 'calendar.platform': 'Platform:', 'calendar.platforms': 'Platforms', 'calendar.unknownVehicle': 'Unknown Vehicle',
    'alerts.title': 'Alerts & Issues', 'alerts.active': 'active alert', 'alerts.actives': 'active alerts', 'alerts.critical': 'critical', 'alerts.allAlerts': 'All Alerts', 'alerts.activeOnly': 'Active', 'alerts.resolved': 'Resolved', 'alerts.allSeverity': 'All Severity', 'alerts.warning': 'Warning', 'alerts.info': 'Info', 'alerts.allClear': 'All Clear!', 'alerts.noMatch': 'No alerts match your current filters', 'alerts.resolution': 'Resolution:', 'alerts.resolvedOn': 'Resolved on', 'alerts.markResolved': 'Mark as Resolved', 'alerts.dismiss': 'Dismiss',
    'alertType.vehicle_unclear': 'Vehicle Name Unclear', 'alertType.dates_missing': 'Dates Missing', 'alertType.ambiguous_update': 'Ambiguous Booking Update', 'alertType.sync_conflict': 'Sync Conflict', 'alertType.low_confidence': 'Low Confidence', 'alertType.connection_error': 'Connection Error',
    'email.title': 'Email Activity', 'email.subtitle': 'Audit log of all processed emails', 'email.search': 'Search by subject or sender...', 'email.allActions': 'All Actions', 'email.synced': 'Synced', 'email.blocked': 'Blocked', 'email.pendingReview': 'Pending Review', 'email.ignored': 'Ignored', 'email.noEmails': 'No emails found', 'email.noProcessed': 'No emails have been processed yet', 'email.adjustFilters': 'Try adjusting your filters', 'email.noSubject': 'No subject', 'email.eventType': 'Event Type', 'email.confidence': 'Confidence', 'email.preview': 'Email Preview', 'email.classificationOutput': 'Classification Output',
    'eventType.booking_confirmed': 'Booking Confirmed', 'eventType.booking_cancelled': 'Booking Cancelled', 'eventType.booking_modified': 'Booking Modified', 'eventType.reminder': 'Reminder', 'eventType.unknown': 'Unknown',
    'settings.title': 'Settings', 'settings.subtitle': 'Manage your connections and preferences', 'settings.emailConnected': 'Email Connected', 'settings.emailNotConnected': 'Email Not Connected', 'settings.connectedVia': 'Connected via', 'settings.connectToStart': 'Connect to start syncing', 'settings.calendarConnected': 'Calendar Connected', 'settings.calendarNotConnected': 'Calendar Not Connected', 'settings.syncingTo': 'Syncing to', 'settings.optionalSync': 'Optional - sync to calendar', 'settings.emailConnection': 'Email Connection', 'settings.emailConnectionDesc': 'Connect your Gmail or Outlook to automatically receive booking notifications', 'settings.calendarSync': 'Calendar Sync', 'settings.calendarSyncDesc': 'Sync bookings to your preferred calendar for a unified view', 'settings.clickToConnect': 'Click to connect', 'settings.connected': 'Connected', 'settings.icalIntegration': 'iCal Integration', 'settings.icalDesc': 'Share booking calendars with rental platforms', 'settings.setupInstructions': 'Setup Instructions', 'settings.icalInstructions': 'After adding vehicles, you\'ll receive unique iCal URLs for each vehicle. Copy these URLs into Turo, Getaround, or other platforms to sync your bookings and prevent double bookings.', 'settings.language': 'Language', 'settings.languageDesc': 'Choose your interface language', 'settings.french': 'Français', 'settings.english': 'English', 'settings.general': 'General', 'settings.notifications': 'Notifications', 'settings.calendars': 'Calendars', 'settings.subscription': 'Subscription', 'settings.maintenance': 'Maintenance', 'settings.revenue': 'Revenue', 'settings.autoDetection': 'Automatic Vehicle Detection', 'settings.autoDetectionDesc': 'Add your vehicles automatically via emails', 'settings.autoDetectionInfo': 'FleetSync automatically detects new vehicles mentioned in your booking emails (Turo, Getaround, Hunos Rent) and suggests adding them to your fleet.', 'settings.featureActive': 'Feature Active', 'settings.featureActiveDesc': 'Connect your email above and new vehicles will be automatically detected when booking confirmations are received.', 'settings.calendarIntegrations': 'Calendar Integrations', 'settings.comingSoon': 'Coming Soon', 'settings.maintenanceComingSoon': 'Maintenance integrations will be available soon', 'settings.revenueComingSoon': 'Revenue integrations will be available soon',
    'notifPrefs.title': 'Notification Preferences', 'notifPrefs.description': 'Choose which notifications you want to receive', 'notifPrefs.upcomingBookings': 'Upcoming Bookings', 'notifPrefs.upcomingBookingsDesc': 'Notification 24h before a booking starts', 'notifPrefs.vehicleReturns': 'Vehicle Returns', 'notifPrefs.vehicleReturnsDesc': 'Notification on the day a vehicle is expected back', 'notifPrefs.statusUpdates': 'Status Updates', 'notifPrefs.statusUpdatesDesc': 'Notification when a booking status changes', 'notifPrefs.syncErrors': 'Sync Errors', 'notifPrefs.syncErrorsDesc': 'Alert when there\'s a synchronization issue', 'notifPrefs.newAlerts': 'New Alerts', 'notifPrefs.newAlertsDesc': 'Notification when a new alert is created', 'notifPrefs.saved': 'Preferences saved',
    'calendarIntegrations.backendRequiredTitle': 'FleetSync server', 'calendarIntegrations.backendRequiredDesc': 'Google and Outlook calendars are handled by the FleetSync server. Add the backend OAuth credentials to push events outside. Without them, bookings stay in the local calendar.', 'calendarIntegrations.googleCalendar': 'Google Calendar', 'calendarIntegrations.googleCalendarDesc': 'Sync your bookings with Google Calendar for a unified view', 'calendarIntegrations.googleConnected': 'Active sync with Google Calendar', 'calendarIntegrations.outlookCalendar': 'Outlook Calendar', 'calendarIntegrations.outlookCalendarDesc': 'Integrate your bookings with your professional Outlook calendar', 'calendarIntegrations.outlookConnected': 'Active sync with Outlook Calendar', 'calendarIntegrations.backendRequired': 'Add the FleetSync server OAuth credentials to push this calendar outside', 'calendarIntegrations.disconnected': 'Calendar disconnected',
    'integrationCard.connected': 'Connected', 'integrationCard.notConnected': 'Not connected', 'integrationCard.connect': 'Connect', 'integrationCard.connecting': 'Connecting...', 'integrationCard.disconnect': 'Disconnect', 'integrationCard.disconnecting': 'Disconnecting...',
    'notification.new_booking': 'New Booking', 'notification.booking_cancelled': 'Booking Cancelled', 'notification.booking_modified': 'Booking Modified', 'notification.vehicle_status_change': 'Vehicle Status Changed', 'notification.maintenance_reminder': 'Maintenance Reminder', 'notification.sync_error': 'Sync Error', 'notification.alert_created': 'New Alert',
    'notification.New Booking': 'New Booking', 'notification.Booking Cancelled': 'Booking Cancelled', 'notification.Booking Modified': 'Booking Modified', 'notification.Vehicle Status Changed': 'Vehicle Status Changed', 'notification.Maintenance Reminder': 'Maintenance Reminder', 'notification.Sync Error': 'Sync Error', 'notification.New Alert': 'New Alert',
    'notifications.title': 'Notifications', 'notifications.unreadCount': '{{count}} unread', 'notifications.markAllRead': 'Mark all read', 'notifications.empty': 'No notifications yet',
    'analytics.title': 'Analytics Dashboard', 'analytics.subtitle': 'Overview of your performance and metrics', 'analytics.totalBookings': 'Total Bookings', 'analytics.monthlyRevenue': 'Monthly Revenue', 'analytics.weeklyRevenue': 'Weekly Revenue', 'analytics.activeBookings': 'Active Bookings', 'analytics.revenue': 'Revenue', 'analytics.utilization': 'Utilization', 'analytics.platforms': 'Platforms', 'analytics.revenueEvolution': 'Revenue Evolution', 'analytics.revenueEvolutionDesc': 'Net revenue from the last 6 months', 'analytics.revenueLabel': 'Revenue', 'analytics.revenueEuro': 'Revenue (€)', 'analytics.utilizationRate': 'Vehicle Utilization Rate', 'analytics.utilizationRateDesc': 'Usage percentage this month', 'analytics.utilizationLabel': 'Utilization', 'analytics.utilizationPercent': 'Utilization (%)', 'analytics.platformDistribution': 'Platform Distribution', 'analytics.platformDistributionDesc': 'Booking distribution by platform',
    'clients.title': 'Customers', 'clients.subtitle': 'Manage your customers and their history', 'clients.addCustomer': 'Add Customer', 'clients.searchPlaceholder': 'Search by name, email or phone...', 'clients.allPlatforms': 'All Platforms', 'clients.manual': 'Manual', 'clients.loading': 'Loading...', 'clients.noCustomersFound': 'No customers found', 'clients.noCustomers': 'No customers', 'clients.adjustFilters': 'Try adjusting your filters', 'clients.addFirstCustomer': 'Add your first customer', 'clients.bookings': 'Bookings',
    'users.title': 'User Management', 'users.subtitle': 'Manage your team members and their permissions', 'users.inviteUser': 'Invite User', 'users.searchPlaceholder': 'Search by name or email...', 'users.role': 'Role', 'users.allRoles': 'All Roles', 'users.admin': 'Admin', 'users.manager': 'Manager', 'users.user': 'User', 'users.noName': 'No name', 'users.department': 'Department', 'users.edit': 'Edit', 'users.noUsersFound': 'No users found', 'users.updateSuccess': 'User updated successfully', 'users.deleteSuccess': 'User deleted successfully', 'users.deleteError': 'Error deleting user', 'users.confirmDelete': 'Are you sure you want to delete {{name}}?', 'users.accessDenied': 'Access Denied', 'users.accessDeniedDesc': 'You don\'t have permissions to access this page.',
    'subscription.fleetSyncPlan': 'FleetSync Plan', 'subscription.activeSubscription': 'Active subscription', 'subscription.active': 'Active', 'subscription.basePlan': 'Base subscription', 'subscription.vehicle': 'vehicle', 'subscription.vehicles': 'vehicles', 'subscription.month': 'month', 'subscription.totalPerMonth': 'Total per month', 'subscription.pricingTiers': 'Progressive pricing', 'subscription.autoDegressivePricing': 'The more your fleet grows, the less you pay per vehicle', 'subscription.includedFeatures': 'Included features', 'subscription.syncMultiPlatform': 'Multi-platform sync', 'subscription.realTimeAlerts': 'Real-time alerts', 'subscription.calendarIntegration': 'Calendar integration', 'subscription.emailProcessing': 'Automatic email processing', 'subscription.unlimitedBookings': 'Unlimited bookings', 'subscription.support': 'Customer support', 'subscription.managePayment': 'Manage payment', 'subscription.cancelSubscription': 'Cancel subscription', 'subscription.noCommitment': 'No commitment • Cancel anytime', 'subscription.contactSupport': 'Contact support to manage your subscription', 'subscription.stripePortalInfo': 'To enable Stripe payment management, please configure Stripe integration in your app', 'subscription.portalError': 'Error opening payment portal', 'subscription.fixedPrice': 'flat rate', 'subscription.upTo': 'Up to',
    'rgpd.title': 'GDPR Compliance', 'rgpd.subtitle': 'Manage your consents and privacy preferences', 'rgpd.consentGiven': 'Full consent given', 'rgpd.consentPending': 'Incomplete consent', 'rgpd.active': 'Active', 'rgpd.incomplete': 'Incomplete', 'rgpd.lastUpdate': 'Last update', 'rgpd.emailProcessing': 'Booking email processing', 'rgpd.emailProcessingDesc': 'I authorize FleetSync to process my booking emails from authorized rental platforms', 'rgpd.dataRetention': 'Data retention', 'rgpd.dataRetentionDesc': 'I accept the retention of my booking data in accordance with the privacy policy', 'rgpd.allowedDomains': 'Allowed domains', 'rgpd.allowedDomainsDesc': 'FleetSync will only process emails from these secure domains:', 'rgpd.saveConsent': 'Save preferences', 'rgpd.saving': 'Saving...', 'rgpd.consentSaved': 'Preferences saved', 'rgpd.dataRights': 'In accordance with GDPR, you have the right to access, rectify, erase and port your data. You can withdraw your consent at any time. To exercise your rights, contact support.', 'rgpd.backendRequired': 'Email filtering (Backend required)', 'rgpd.backendRequiredDesc': 'The FleetSync server only processes imported emails whose sender belongs to the allowed domains.',
    'login.title': 'Sign In', 'login.subtitle': 'Access your FleetSync account', 'login.email': 'Email address', 'login.emailPlaceholder': 'your@email.com', 'login.emailRequired': 'Email is required', 'login.emailInvalid': 'Please enter a valid email address', 'login.password': 'Password', 'login.passwordPlaceholder': '••••••••', 'login.passwordRequired': 'Password is required', 'login.passwordTooShort': 'Password must be at least 6 characters', 'login.rememberMe': 'Remember me', 'login.forgotPassword': 'Forgot password?', 'login.signIn': 'Sign In', 'login.loggingIn': 'Signing in...', 'login.noAccount': 'Don\'t have an account?', 'login.signUp': 'Sign Up', 'login.backToHome': 'Back to home', 'login.securityNote': 'Your data is encrypted and secure', 'login.success': 'Login successful', 'login.failed': 'Login failed', 'login.orContinueWith': 'Or continue with', 'login.continueWithGoogle': 'Continue with Google', 'login.googleLoginFailed': 'Google login failed',
    'register.title': 'Create Account', 'register.subtitle': 'Get started with FleetSync', 'register.name': 'Full Name', 'register.namePlaceholder': 'John Doe', 'register.nameRequired': 'Name is required', 'register.email': 'Email address', 'register.emailPlaceholder': 'your@email.com', 'register.emailRequired': 'Email is required', 'register.emailInvalid': 'Please enter a valid email address', 'register.password': 'Password', 'register.passwordPlaceholder': '••••••••', 'register.passwordRequired': 'Password is required', 'register.passwordTooShort': 'Password must be at least 6 characters', 'register.createAccount': 'Create Account', 'register.creatingAccount': 'Creating account...', 'register.alreadyHaveAccount': 'Already have an account?', 'register.signIn': 'Sign In', 'register.backToHome': 'Back to home', 'register.termsAgreement': 'By signing up, you agree to our Terms of Service and Privacy Policy', 'register.success': 'Account created successfully', 'register.failed': 'Account creation failed', 'register.orContinueWith': 'Or continue with', 'register.continueWithGoogle': 'Continue with Google', 'register.googleSignupFailed': 'Google signup failed',
    'authCallback.processing': 'Processing authentication...', 'authCallback.pleaseWait': 'Please wait while we process your login', 'authCallback.loginSuccess': 'Login successful', 'authCallback.loginFailed': 'Login failed', 'authCallback.noToken': 'No authentication token received',
    'login.continueWithMicrosoft': 'Continue with Microsoft', 'register.continueWithMicrosoft': 'Continue with Microsoft', 'login.microsoftLoginFailed': 'Microsoft login failed', 'register.microsoftSignupFailed': 'Microsoft signup failed',
    }
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export const LanguageProvider = ({ children }) => {
  const getInitialLanguage = () => {
    const saved = localStorage.getItem('fleetsync_language');
    if (saved) return saved;
    const browserLang = navigator.language.toLowerCase();
    return browserLang.startsWith('fr') ? 'fr' : 'en';
  };

  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    localStorage.setItem('fleetsync_language', language);
  }, [language]);

  const t = (key) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};